export { AdminAuthController } from './auth.controller';
export * from './analytics.controller';
export * from './user.controller';
export * from './course.controller';
export * from './section.controller';
export * from './lesson.controller';
export * from './assignment.controller';
export * from './submission.controller';
export * from './announcement.controller';
export * from './system.controller';
export * from './support.controller';
